# Generated by Django 5.2.8 on 2025-11-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty_pref',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
